apiVersion: apps/v1
kind: Deployment
metadata:
  name: redbici-v1
  labels:
    app: redbici
    version: "1.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redbici
  template:
    metadata:
      labels:
        app: redbici
        version: "1.0"
    spec:
      containers:
      - name: redbici
        image: alismo1013/redbici:latest
        ports:
        - name: http-server
          containerPort: 3000
